{{- if .Values.coda.runtimeConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{$.Values.snarkSetConfigs.coordinatorName }}-daemon-config
  labels:
    app: snark-coordinator
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  daemon.json: {{ .Values.coda.runtimeConfig | quote }}
{{- end }}
