{{ range $config := $.Values.snarkSetConfigs}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{tpl $config.workerName .}}
  labels:
    app: {{tpl $config.workerName .}}
spec:
  replicas: {{ .Values.worker.numReplicas }}
  selector:
    matchLabels:
      app: {{tpl $config.workerName .}}
  template:
    metadata:
      labels:
        app: {{tpl $config.workerName .}}
        testnet: {{ .Values.testnetName }}
        role: snark-worker
        version: {{ trunc 6 (split ":" .Values.coda.image)._1 | trimSuffix "-" }}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '10000'
        prometheus.io/path: '/metrics'
    spec:
      containers:
      - name: worker
        resources:
          limits:
            memory: 16.0Gi
          requests:
            memory: 6.0Gi
            cpu: 4
        image: {{ .Values.coda.image }}
        {{ if $.Values.coda.useCustomEntrypoint -}}
        command: [{{ $.Values.coda.customEntrypoint }}]
        {{- else }}
        command: ["bash", "-c"]
        {{- end }}
        args: [ "sleep 120 && mina internal snark-worker -proof-level full -daemon-address '{{ tpl $config.coordinatorHostName . }}:{{ $config.coordinatorRpcPort }}'" ]
        env:
          - name: "RAYON_NUM_THREADS"
            value: "4"
        imagePullPolicy: Always
{{- include "nodeSelector.preemptible" .Values | indent 6 }}
{{ end }}
